### ISSUE TITLE
Dealing with sub-theme stylesheet (get it after parent)

### ISSUE THREAD

**Issue by findlabnet** [backdrop-contrib/minicss#2]
Here is answer to forum topic: https://forum.backdropcms.org/forum/minicss-subtheme-css

**Updated: - please DO NOT use approach described below, I've defined it as bug - fixed in ver.1.0.2 (2019-03-02)**. 
--------------------------------------------------------------------------
To get thing done you need add to your template.php new function like this:
```php
function YOUR_THEME_NAME_css_alter(&$css) {
  // Please note 'weight' value should be positive to go after parent theme styles
  $substyle = backdrop_get_path('theme', 'YOUR_THEME_NAME') . '/css/YOUR_FILE_NAME.css';
  $css[$substyle] = array(
    'data' => $substyle,
    'type' => 'file',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => TRUE,
    'group' => CSS_THEME,
    'browsers' => array('IE' => TRUE, '!IE' => TRUE),
    'weight' => 9,
  );
}
```
This information should be added to README.md for new release.

**Comment by Wylbur** [comment]
I added the following to my subtheme, but now the subtheme style sheet is not rendering at all.  I'll write up documentation patch for this once we get this working!

amnesty.info
> > name = Amnesty Group Website Theme
> description = Amnesty local group website theme built on MiniCSS theme 02/28/19
> backdrop = 1.x
> base theme = minicss
> version = 1.0

template.php
> <?php 
> function amnesty_css_alter(&$css) {
>   // Add css files
>   // Please note 'weight' value should be positive to go after parent theme styles  
>   $amnestycss = backdrop_get_path('theme', 'amnesty') . 'amnesty.css';
>   $css[$amnestycss] = array(
>     'data' => $amnestycss,
>     'type' => 'file',
>     'every_page' => TRUE,
>     'media' => 'all',
>     'preprocess' => TRUE,
>     'group' => CSS_THEME,
>     'browsers' => array('IE' => TRUE, '!IE' => TRUE),
>     'weight' => 9,
>   );
> }

amnesty.css
> :root {
>   --footer-color: #fff;
>   --footer-background: #000;
>   --footer-link-color: #fff;
> }
> footer {
>     background-color: var(--footer-background);
>     color: var(--footer-color);
> }
> .l-footer a, .l-footer a:visited {
>   color: var(--footer-link-color);
>   text-decoration: underline;
>   font-weight: bold;
> }

**Comment by findlabnet** [comment]
Please try to place in your template.php exactly this function:

```php
function amnesty_css_alter(&$css) {
  $substyle = backdrop_get_path('theme', 'amnesty') . '/css/amnesty.css';
  $css[$substyle] = array(
    'data' => $substyle,
    'type' => 'file',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => TRUE,
    'group' => CSS_THEME,
    'browsers' => array('IE' => TRUE, '!IE' => TRUE),
    'weight' => 9,
  );
}
```
Also, make sure file amnesty.css is placed in `css` sub-directory of your sub-theme directory (very likely named `amnesty`).

This should works as expected, I've tested it.

**Additional tip:** before you redefine variables in your css - try some more simple approach, 
for example declare something like:
```css
* {background-color: red}
```
then **clear cache/theme registry** and check result and order of included css files in rendered html.

Thank you for reporting!

**Comment by herbdool** [comment]
Interesting problem. I don't know how but it might be useful to make this default. I think most people would consider the subtheme styles to always override the parent theme.

**Comment by herbdool** [comment]
This thread might help. Describes how to structure parent theme so that child themes render after parent. http://www.drupal.org/forum/support/module-development-and-code-questions/2014-11-16/base-theme-css-rendering-order-with

**Comment by findlabnet** [comment]
@herbdool, many thanks - as usual, every bug someone did already! 
(group should be CSS_DEFAULT instead CSS_THEME as it here)
Bugfix release coming soon.

**Comment by findlabnet** [comment]
[Version 1.x-1.0.2](https://github.com/backdrop-contrib/minicss/releases/tag/1.x-1.0.2) is released as bug-fix for this issue.
For now "hackish" approach described above do not need anymore (but can works if any need).
Thanks to all for help!

**Comment by Wylbur** [comment]
The Backdrop documentation clearly states how to create subthemes. These instructions do not work for this module.  
https://api.backdropcms.org/documentation/creating-sub-themes
Using a subtheme is a preferred approach to customizing a backdrop theme, which brings many benefits and features. 

Anyone coming from Drupal 7 expects themes to be subthemable.  This does not work with this theme.  This theme does not mention that on it's project page or README file.  

When I use a theme, I expect it to be subthemable so I don't have to hack the module to add style changes within the base theme where they can be overwritten.  I'm also adding template file changes to this theme as part of my subtheme.  Same for JS.  Adding CSS theming to the base theme is never recommended.  

This approach will bring frustration and confusion to long time users of Drupal and new users of Backdrop.  If this is the approach of this module, it should be removed from the Backdrop project page.  

My intention in bringing up this issue is to make this theme usable for new users that discover this theme.  I have already spent a few days trying to get this working.  It has been frustrating and non-standard.  Every new user of this theme should not have to do through this process. 

I understand your approach was to use the theme settings forms to select and apply the Theme CSS files.  The approach you are using is breaking subtheming.  This is a big problem.  

The small changes you have made in the README file do not resolve this issue.  

I'm happy to help develop and test this.  Let's get this working as it should.

**Comment by findlabnet** [comment]
As you can see one comment above your, in the latest version (1.0.2) released yesterday this bug is fixed and you and anyone else can build sub-theme as recommended and include your css/js via .info file of your sub-theme.
If I can fix something else, just let me know! 
Thank you!

**Comment by herbdool** [comment]
@findlabnet I was curious about the issue but had to look things up. The thing I understood from the thread I linked above is that the base theme needs to declare the CSS and JS being added in the .info file. Like in Basis https://github.com/backdrop/backdrop/blob/1.x/core/themes/basis/basis.info. I suspect that even if you have CSS_DEFAULT in the alter hook it'll add the CSS with the modules instead of after. See this particular comment https://www.drupal.org/forum/support/module-development-and-code-questions/2014-11-16/base-theme-css-rendering-order-with#comment-9348535. Adding to the .info file makes it easy for subthemes to override the parent CSS without having to write PHP.

I was going to test this when I have a chance.

**Comment by herbdool** [comment]
I just took a look and I see why you chose the alter hook. Perhaps there's a middle ground: you could put the default CSS into the .info file and then with the alter hook unset the default if one other flavor is chosen and add those dynamically. Seems like there's a bit of a compromise between treating this as a base theme and also be used on its own.

**Comment by findlabnet** [comment]
@herbdool thank you for help. 
I'll think about it. 
Main motivation for this theme was not about subtheming, but for playing with dynamic theme settings and classes, provided by framework for custom blocks.
Additional problem for subthemer - setting page, which is inherited from base theme visually, but cannot to save "sub-settings".
This can be resolved by adding some "starterkit" to base theme, but it may add the complexity for beginners.
Anyway, as usual I open for suggestions.
